# Reference docs at https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        threshold: 0.5%

github_checks:
  annotations: false
