name: qibochem
channels:
- conda-forge
- psi4
- defaults
dependencies:
- python=3.9
- psi4=1.7
- numpy
- sympy
- scipy
- pip
- pip:
  - openfermion>=1.5
  - qibo=0.1.10
  - pyscf=2.2.1
