name: Deploy

on:
  push:
  merge_group:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Conda
      uses: ./.github/workflows/conda.yml
      with:
        os: ${{ runner.os }}
        python-version: ${{ matrix.python-version }}
    - name: Deploy workflow
      uses: qiboteam/workflows/.github/workflows/deploy-pip-poetry.yml@main
      with:
        os: ${{ runner.os }}
        python-version: ${{ matrix.python-version }}
        doctests: ${{ runner.os == 'ubuntu-latest'}}
        poetry-extras: "--with docs,tests,analysis --all-extras"
